// I: \Users\welfj\Documents\Programming\MyNameIsTrez.github.io\projects\Twitter > node bot.js
// Running
// Connecting
a = {
	created_at: 'Wed Apr 15 22:44:16 +0000 2020',
	id: 1250555569389346800,
	id_str: '1250555569389346819',
	text: 'test',
	source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
	truncated: false,
	in_reply_to_status_id: null,
	in_reply_to_status_id_str: null,
	in_reply_to_user_id: null,
	in_reply_to_user_id_str: null,
	in_reply_to_screen_name: null,
	user:
	{
		id: 2405684716,
		id_str: '2405684716',
		name: 'MyNameIsTrez',
		screen_name: 'welfje',
		location: null,
		url: null,
		description: null,
		translator_type: 'none',
		protected: false,
		verified: false,
		followers_count: 13,
		friends_count: 299,
		listed_count: 0,
		favourites_count: 45071,
		statuses_count: 731,
		created_at: 'Wed Mar 12 19:57:33 +0000 2014',
		utc_offset: null,
		time_zone: null,
		geo_enabled: false,
		lang: null,
		contributors_enabled: false,
		is_translator: false,
		profile_background_color: 'C0DEED',
		profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
		profile_background_tile: false,
		profile_link_color: '1DA1F2',
		profile_sidebar_border_color: 'C0DEED',
		profile_sidebar_fill_color: 'DDEEF6',
		profile_text_color: '333333',
		profile_use_background_image: true,
		profile_image_url:
			'http://pbs.twimg.com/profile_images/1250537224216641538/QaKuoVv-_normal.jpg',
		profile_image_url_https:
			'https://pbs.twimg.com/profile_images/1250537224216641538/QaKuoVv-_normal.jpg',
		default_profile: true,
		default_profile_image: false,
		following: null,
		follow_request_sent: null,
		notifications: null
	},
	geo: null,
	coordinates: null,
	place: null,
	contributors: null,
	is_quote_status: false,
	quote_count: 0,
	reply_count: 0,
	retweet_count: 0,
	favorite_count: 0,
	entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
	favorited: false,
	retweeted: false,
	filter_level: 'low',
	lang: 'en',
	timestamp_ms: '1586990656598'
}
Attempting to tweet...
Original tweet: test
LuaSchlatt's response: write('test')
Success!
{
	created_at: 'Wed Apr 15 22:44:21 +0000 2020',
		id: 1250555591518552000,
			id_str: '1250555591518552074',
				text: '@welfje write(\'test\')',
					display_text_range: [8, 21],
						source:
	'<a href="https://mynameistrez.github.io/" rel="nofollow">LuaSchlatt</a>',
		truncated: false,
			in_reply_to_status_id: 1250555569389346800,
				in_reply_to_status_id_str: '1250555569389346819',
					in_reply_to_user_id: 2405684716,
						in_reply_to_user_id_str: '2405684716',
							in_reply_to_screen_name: 'welfje',
								user:
	{
		id: 1250532169275052000,
			id_str: '1250532169275052032',
				name: 'LuaSchlatt',
					screen_name: 'LuaSchlatt',
						location: null,
							url: null,
								description: 'write(\'Dick \\\'n Balls\')',
									translator_type: 'none',
										protected: false,
											verified: false,
												followers_count: 1,
													friends_count: 2,
														listed_count: 0,
															favourites_count: 0,
																statuses_count: 8,
																	created_at: 'Wed Apr 15 21:11:23 +0000 2020',
																		utc_offset: null,
																			time_zone: null,
																				geo_enabled: false,
																					lang: null,
																						contributors_enabled: false,
																							is_translator: false,
																								profile_background_color: 'F5F8FA',
																									profile_background_image_url: '',
																										profile_background_image_url_https: '',
																											profile_background_tile: false,
																												profile_link_color: '1DA1F2',
																													profile_sidebar_border_color: 'C0DEED',
																														profile_sidebar_fill_color: 'DDEEF6',
																															profile_text_color: '333333',
																																profile_use_background_image: true,
																																	profile_image_url:
		'http://pbs.twimg.com/profile_images/1250532225638072322/ZiR9dsoe_normal.jpg',
			profile_image_url_https:
		'https://pbs.twimg.com/profile_images/1250532225638072322/ZiR9dsoe_normal.jpg',
			default_profile: true,
				default_profile_image: false,
					following: null,
						follow_request_sent: null,
							notifications: null
	},
	geo: null,
		coordinates: null,
			place: null,
				contributors: null,
					is_quote_status: false,
						quote_count: 0,
							reply_count: 0,
								retweet_count: 0,
									favorite_count: 0,
										entities:
	{
		hashtags: [],
			urls: [],
				user_mentions: [[Object]],
					symbols: []
	},
	favorited: false,
		retweeted: false,
			filter_level: 'low',
				lang: 'en',
					timestamp_ms: '1586990661874'
}
// Attempting to tweet...
// Original tweet: @welfje write('test')
// LuaSchlatt's response: write('@welfje write(\'test')')
// Success!